





















































































































































































/****** Object:  StoredProcedure [dbo].[Utility_ShowIndex]    Script Date: 01/12/2018 15:31:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
----------------------------------------------------------------------------

--------------------------------------------------------------------------------------

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG='BW_Sandbox02'
Order by Table_Name
 --(for MySql, use: TABLE_SCHEMA='dbName' )




--------------------------------------------------------------------------------------
--
*/




Create PROCEDURE [dbo].[Utility_ResetToNew]

 AS

SET NOCOUNT ON


-- Delete all device data







Select * from Category -- Leave these as they are.
----------------------------------------------------------------
-- Keep (mostlikely)
/*
Category
ClientStatus
ClientLocationStatus
CommandCode
DeviceCatalogue
HolidaySchedule
MasterClass
MasterFunctionTable
MasterHoliday
MasterIFSLocation
MasterIFSLocationPurpose
MasterIFSLocationStatus
MasterPartsClassType
MasterSKUStatus
OptionStatus
OptionType
PartNumberBucketInventoryTransactionType
ProcessStatus
NextProcessStepStatus
ProjectStatus
QuestionStatus
QuestionType
ReceiveDetailStatus
SystemData




Project
ProjectProcess
Process
NextProcessStep
ProcessBinLocation
ProcessQuestion
Question
QuestionDependencies
Option
Option_Text_Defaults




*/





Select * from CycleCountInventoryCount
---------------------------------------------------------
-- RD Misc
/*
CycleCountInventoryCount
CycleCountInventoryCountParts
CycleInventoryCountControlDetail
CycleInventoryCountControlDetailParts
CycleInventoryCountHeader
CycleInventoryCountHeaderParts
CycleInventoryCountIterationDetail
CycleInventoryCountIterationDetailParts
CycleInventoryCountIterationHeader
CycleInventoryCountIterationHeaderParts
CycleInventoryCountTemplateHeader
CycleInventoryCountTemplateHeaderDetail
CycleInventoryCountTemplateHeaderParts
CycleInventoryCountTemplateHeaderPartsDetail
PhysicalInventoryCount
PhysicalPartInventoryCount





GetMasterDetailInventoryClientList_IMEIBatch
GridCCRunBatchesControl
GridCCRunBatchesControlParts
GridCCRunBatchesControlS
IFS_GatherLog
IFSPickListOrderCompany
IFSPickListOrderDetail
IFSPickListOrderHeader
IFSPurchaseOrderDetail
IFSPurchaseOrderHeader
IFSXMLFileHeader
InvtTran_IFS
InvtTran_IFS_Analyze
InvtTran_IFS_ErrorLog
InvtTran_IFSDirective
InvtTran_IFSDirectiveLog
JimErrorLog
LocationLog
MasterBucketTransactions
MasterCarrierManufacturerLookup
MasterCarrierManufacturerStatus
MasterFileTransferDetailLog
MasterFileTransferLog
MasterModelMemoryLookup
MasterSKU


*/

Select * from AutoGeneratedPONumbers
---------------------------------------------------------
-- RD Misc
/*
MasterParts
MasterPartsLinkTable
MasterPartsLinkTableModelList
MasterPartsLinkTableMonthEnd
MasterPartsLinkTablePriceList
MasterPartsLinkTablePriceList_ChangeLog
MasterPartsRequestedLog
MasterPartsTableIFSLocationStorage
MasterPartsTableIFSLocationStorageChangeLog
MasterPartsTableIFSLocationStorageMoveLog
MasterPartsTechAssignedLog
PartNumberBucketInventoryPlacement
PartNumberBucketInventorySource


*/

Select * from AutoGeneratedPONumbers
---------------------------------------------------------
-- RD Misc
/*



*/








PurchaseOrderHeader
OrderCompany
OrderDetail
OrderDetailReceiveDetail
OrderHeader
OrderMoveChangeLog
OrderMoveLog
OrderMoveShipToDoneLog
OrderStatus
SOCompany
SODetail
SODetailReceiveDetail
SOHeader
SOMoveLog
SOPickListDetail
SOPickListHeader




StatisticalRawBucketData
StatisticalRawBucketDataGrandTotal
StatisticalRawData
Discrepancy
DiscrepancyDDRelations



ReceiveDetail
ReceiveDetail_BagtagPreSaveData
ReceiveDetailAuthorizationLog
ReceiveDetailAuthorizationStatus
ReceiveDetailBillingPoints
ReceiveDetailBinLog
ReceiveDetailBulk
ReceiveDetailBulkProcessLog
ReceiveDetailClientContactLog
ReceiveDetailClientSubmitted
ReceiveDetailConditionChangeLog
ReceiveDetailCostingLog
ReceiveDetailErrorReporting
ReceiveDetailESNMessage
ReceiveDetailExcelUploadLog
ReceiveDetailHeaderChangeLog
ReceiveDetailHobbleList
ReceiveDetailIFSInOutLog
ReceiveDetailIFSLocationLog
ReceiveDetailIMEIChangedLog
ReceiveDetailIMEISwappedLog
ReceiveDetailItem
REceiveDetailItem_Archive
ReceiveDetailItem_Archive_01
ReceiveDetailItem_Archive_02
ReceiveDetailItem_Deleted_01
ReceiveDetailItemBulk
ReceiveDetailNotationLog
ReceiveDetailPartsUsage
ReceiveDetailPreReceive
ReceiveDetailPreReceiveAttribute
ReceiveDetailProcessLog
ReceiveDetailSaveLog
ReceiveDetailSaveTransaction
ReceiveDetailSKUChangeLog
ReceiveDetailTriggerLog
ReceiveDetailUtilityRunLog
ReceiveDetailVersionChangeLog
ReceiveDetailVersionChangeLogSource
ReceiveDetailXBINXDetailLog
ReceiveDetailXBINXHeaderLog
ReceiveDetailXBinXLocationLog
ReceiveDockingCounts
ReceiveHeader















SET NOCOUNT OFF
Select * from AutoGeneratedPONumbers
---------------------------------------------------------------
-- Misc to clean out.
/*

Delete AutoGeneratedPONumbers
Delete AutoGeneratedPONumbers_B
Delete BinLocation
Delete BishopCatalogueSendLog
Delete CCRunBatchesScanResult
Delete DataDrop
Delete DataDropColumn
Delete MasterProcessWaitTimes
Delete UnitItemStatus

SystemLog
SystemTimeLog
ScanCodeLog
EmailLog
RequestProcessCompletionList
ReservedAvailableStock

*/











Select * from AutoGeneratedPONumbers
---------------------------------------------------------
-- RD Misc
/*



*/

Select * from Client
-------------------------------------------------
-- Client Related Stuff.
/*
Client
ClientAnswerRestrict
ClientBillingPoints
ClientLocation
ClientProcessDependencies
ClientProjectDependencies
ClientQuestionRestrict


*/

-- Delete all users except Admin and jmccomb
aspnet_Applications
aspnet_Membership
aspnet_Paths
aspnet_PersonalizationAllUsers
aspnet_PersonalizationPerUser
aspnet_Profile
aspnet_Roles
aspnet_SchemaVersions
aspnet_Users
aspnet_UsersInRoles
aspnet_WebEvent_Events
RoleAccessTable
RoleMenuAccess
UserAccessTable
UserStatus
UserTable

MasterTableAcccessList





















