/****** Object:  StoredProcedure [dbo].[Update_ReceiveDetailPhysicalScan]    Script Date: 05/19/2015 23:20:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
/*

Declare	@PONumber nvarchar(50)
Declare @POLine nvarchar(5)
    
Exec GetNextPONumberAndLine_B
	'Site',
	'IFSProject',
	'IFSSKUx',
	'POVendor1',
	'jmccomb',
	@PONumber output,
    @POLine Output
    
Print  	@PONumber
Print   @POLine   


Select * from AutoGeneratedPONumbers_B

Update AutoGeneratedPONumbers_B set StatusID = 2

*/



Alter PROCEDURE [dbo].[GetNextPONumberAndLine_B]
	@IFSSite nvarchar(5),
	@IFSProject nvarchar(10),
	@SKU nvarchar(25),
	--@IFSLocation nvarchar(20),
	--@IFSCondition nvarchar(50),
	@POVendor nvarchar(50),
	@UserName nvarchar(50),
	@PONumber nvarchar(50) output,
    @POLine [nvarchar](5) Output
AS
BEGIN
set nocount on
Declare @_POLine smallint 
Declare @AutoGeneratedPONumbersID [numeric](18,0)

if Exists(Select * from AutoGeneratedPONumbers_B where IFSSite = @IFSSite and IFSProject = @IFSProject and SKU = @SKU and POVendor = @POVendor and StatusID = 1)
   begin
   Select @AutoGeneratedPONumbersID = AutoGeneratedPONumbersID,
          @_POLine = POLine, 
          @PONumber = PONumber from AutoGeneratedPONumbers_B where IFSSite = @IFSSite
                                                               and IFSProject = @IFSProject
                                                               and SKU = @SKU
                                                               and POVendor = @POVendor
												               and StatusID = 1
   Select @POLine = convert(nvarchar(5),@_POLine)
   Return
   End		  									               


if Exists(Select * from AutoGeneratedPONumbers_B where IFSSite = @IFSSite and IFSProject = @IFSProject and POVendor = @POVendor and StatusID = 1)
   begin
   Select Top 1 
          @AutoGeneratedPONumbersID = AutoGeneratedPONumbersID,
          @_POLine = POLine, 
          @PONumber = PONumber from AutoGeneratedPONumbers_B where IFSSite = @IFSSite
                                                               and IFSProject = @IFSProject
                                                               and POVendor = @POVendor
												               and StatusID = 1 Order by POLine Desc
												               
   Select @_POLine = @_POLine + 1
   Insert AutoGeneratedPONumbers_B ([IFSSite],[IFSProject],[Sku],[IFSCondition],[IFSLocation],[POVendor],[PONumber],[POLine],[StatusID],[CreatedDate],[CreateUser],[LastUpdateDate],[LastUpdateUser])
   Values(@IFSSite,@IFSProject,@SKU,'','',@POVendor,@PONumber,@_POLine,1,getdate(),@UserName,getdate(),@UserName)   
   Select @POLine = convert(nvarchar(5),@_POLine)
   Return
   End		  									               

-- WE need to create a new PO, the old one was not found
Select Top 1 @PONumber = PONumber from AutoGeneratedPONumbers_B
 order by PONumber Desc

if (len(isnull(@PONumber,'')) < 12)
   Select @PONumber = 'BRC000000000'
   
Declare @Counter numeric(9)
Select @Counter = convert(Numeric(9),Substring(@PONumber,4,9))
Select @Counter = @Counter + 1
Select @_POLine = 1
Select @PONumber = 'BRC' + Right('000000000' + convert(nvarchar(9),@Counter),9)

Insert AutoGeneratedPONumbers_B ([IFSSite],[IFSProject],[Sku],[IFSCondition],[IFSLocation],[POVendor],[PONumber],[POLine],[StatusID],[CreatedDate],[CreateUser],[LastUpdateDate],[LastUpdateUser])
Values(@IFSSite,@IFSProject,@SKU,'','',@POVendor,@PONumber,@_POLine,1,getdate(),@UserName,getdate(),@UserName)   
Select @POLine = convert(nvarchar(5),@_POLine)
       
Return 0

END





