
/*

Drop table MasterIFSLocationPurpose
Drop table MasterIFSLocationStatus
Drop table MasterIFSLocation
Drop Table InvtTran_IFS
Drop table MasterIFSLocation


*/

/****** Object:  Table [dbo].MasterIFSLocationPurpose    Script Date: 05/07/2015 16:23:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].MasterIFSLocationPurpose(
	[MasterIFSLocationPurposeID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[Purpose] [varchar](20) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
	[LastUpdateDate] [datetime] NOT NULL,
	[LastUpdateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterIFSLocationPurpose] PRIMARY KEY CLUSTERED 
(
	[MasterIFSLocationPurposeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO



ALTER TABLE [dbo].MasterIFSLocationPurpose ADD  CONSTRAINT [DF_MasterIFSLocationPurpose_CreateDate]  DEFAULT (getdate()) FOR [CreateDate]
GO


Insert MasterIFSLocationPurpose (Purpose, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser) values ('Stock',getdate(), 'jmccomb',getdate(), 'jmccomb')
Insert MasterIFSLocationPurpose (Purpose, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser) values ('Quarantine',getdate(), 'jmccomb',getdate(), 'jmccomb')
Insert MasterIFSLocationPurpose (Purpose, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser) values ('Staging',getdate(), 'jmccomb',getdate(), 'jmccomb')
Insert MasterIFSLocationPurpose (Purpose, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser) values ('Action',getdate(), 'jmccomb',getdate(), 'jmccomb')
Insert MasterIFSLocationPurpose (Purpose, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser) values ('Kan Con',getdate(), 'jmccomb',getdate(), 'jmccomb')


/****** Object:  Table [dbo].MasterIFSLocationStatus    Script Date: 05/07/2015 16:23:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].MasterIFSLocationStatus(
	[MasterIFSLocationStatusID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[Status] [varchar](20) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
	[LastUpdateDate] [datetime] NOT NULL,
	[LastUpdateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterIFSLocationStatus] PRIMARY KEY CLUSTERED 
(
	[MasterIFSLocationStatusID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO



ALTER TABLE [dbo].[MasterIFSLocationStatus] ADD  CONSTRAINT [DF_MasterIFSLocationStatus_CreateDate]  DEFAULT (getdate()) FOR [CreateDate]
GO

Insert MasterIFSLocationStatus (Status, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser)
values ('Active',getdate(), 'jmccomb',getdate(), 'jmccomb')

Insert MasterIFSLocationStatus (Status, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser)
values ('InActive',getdate(), 'jmccomb',getdate(), 'jmccomb')


/*

Drop Table AutoGeneratedPONumbers

*/

/****** Object:  Table [dbo].[AutoGeneratedPONumbers]    Script Date: 05/11/2015 11:59:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AutoGeneratedPONumbers](
	[AutoGeneratedPONumbersID] [numeric](18,0) IDENTITY(1,1) NOT NULL,
	[IFSSite] [nvarchar](5) NULL,
	[IFSProject] [nvarchar](10) NULL,
	[Sku] [nvarchar](25) NULL,
	[IFSCondition] [nvarchar](50) NULL,
	[IFSLocation] [nvarchar](50) NULL,
	[POVendor] [nvarchar](50) NULL,
	[PONumber] [nvarchar](12) NULL,
	[POLine] [nvarchar](5) NULL,
	[StatusID] [numeric](18,0) NULL,         -- 1 = active, 2 = Used
	[CreatedDate] [datetime] NULL,
	[CreateUser] [nvarchar](50) NULL,
	[LastUpdateDate] [datetime] NULL,
	[LastUpdateUser] [nvarchar](50) NULL,

 CONSTRAINT [PK_AutoGeneratedPONumbers] PRIMARY KEY CLUSTERED 
(
	[AutoGeneratedPONumbersID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


Create Index AGPO_PONumber on AutoGeneratedPONumbers(PONumber)
Create Index AGPO_IFSSite on AutoGeneratedPONumbers(IFSSite)
Create Index AGPO_IFSProject on AutoGeneratedPONumbers(IFSProject)
Create Index AGPO_SKU on AutoGeneratedPONumbers(SKU)
Create Index AGPO_IFSCondition on AutoGeneratedPONumbers(IFSCondition)
Create Index AGPO_IFSLocation on AutoGeneratedPONumbers(IFSLocation)
Create Index AGPO_POVendor on AutoGeneratedPONumbers(POVendor)
/*

Drop Table InvtTran_IFS

*/

/****** Object:  Table [dbo].[InvtTran_IFS]    Script Date: 05/11/2015 11:59:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[InvtTran_IFS](
	[InvtTranID] [numeric](18,0) IDENTITY(1,1) NOT NULL,
	[ReceiveDetailID] [numeric](18,0) NULL,
	[ProcessID] [numeric](18, 0) NULL,
	[Quantity] [int] NULL,
	[GMPPartnumber] [nvarchar](30) NULL,	
	[IFSSite] [nvarchar](5) NULL,
	[IFSProject] [nvarchar](10) NULL,
	[POVendor] [nvarchar](50) NULL,
	[PONumber] [nvarchar](12) NULL,
	[POReceiptDate] [nvarchar](10) NULL,
	[POLine] [nvarchar](4) NULL,
	[POCost] [numeric](18, 5) NULL,



	[FromSku] [nvarchar](25) NULL,
	[FromLocation] [nvarchar](50) NULL,
	[FromCondition] [nvarchar](50) NULL,
	[ToSku] [nvarchar](25) NULL,
	[ToLocation] [nvarchar](50) NULL,
	[ToCondition] [nvarchar](50) NULL,
	[ToSKUID] [numeric](18, 0) NULL,
	[ToLocationID] [numeric](18, 0) NULL,
	[ToConditionID] [numeric](18, 0) NULL,
	[Directive] [smallint] NULL,
	[MiscNote] [nvarchar](100) NULL,			
	[StatusID] [numeric](18,0) NULL,
	[CreatedDate] [datetime] NULL,
	[CreateUser] [nvarchar](50) NULL,
	[CreateSource] [nvarchar](25) NULL,
	[RetrievedBatch] [int] NULL,
	[RetrievedDate] [datetime] NULL,
 CONSTRAINT [PK_InvtTran_IFS] PRIMARY KEY CLUSTERED 
(
	[InvtTranID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO




/****** Object:  Table [dbo].MasterIFSLocation    Script Date: 05/07/2015 16:23:38 ******/
SET ANSI_NULLS ON
GO

/*

Drop table MasterIFSLocation
*/

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].MasterIFSLocation(
	[MasterIFSLocationID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[PurposeID] [numeric](18, 0) NOT NULL,
	[StatusID] [numeric](18, 0) NOT NULL,
	[IsWhip] [bit] NOT NULL,
	[IFSLocation] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](100) NULL,
	[DeviceRollup] [nvarchar](50) NULL,
	[PartRollup] [nvarchar](50) NULL,
	[PickLevel] [nvarchar](10) NOT NULL,

	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
	[LastUpdateDate] [datetime] NOT NULL,
	[LastUpdateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterIFSLocation] PRIMARY KEY CLUSTERED 
(
	[MasterIFSLocationID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].MasterIFSLocation ADD  CONSTRAINT [DF_MasterIFSLocation_CreateDate]  DEFAULT (getdate()) FOR [CreateDate]
GO

Create Index MasterIFSLocationPurposeID on MasterIFSLocation([PurposeID])
Go
Create Index MasterIFSLocationStatusID on MasterIFSLocation([StatusID])
Go

/****** Object:  Table [dbo].[MasterPartsTableIFSLocationStorage]    Script Date: 05/07/2015 16:23:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MasterPartsTableIFSLocationStorage](
	[MasterPartsTableIFSLocationStorageID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[MasterPartsTableID] [numeric](18, 0) NOT NULL,
	[MasterIFSLocationID] [numeric](18, 0) NOT NULL,
	[QTY] [smallint] NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
	[LastUpdateDate] [datetime] NOT NULL,
	[LastUpdateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterPartsTableIFSLocationStorage] PRIMARY KEY CLUSTERED 
(
	[MasterPartsTableIFSLocationStorageID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO


/****** Object:  Table [dbo].[PhysicalInventoryCount]    Script Date: 05/07/2015 16:23:38 ******/
SET ANSI_NULLS ON
GO

/*

Drop Table PhysicalInventoryCount

*/

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PhysicalInventoryCount](
	[PhysicalInventoryCountID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ReceiveDetailID] [numeric](18, 0) NOT NULL,
	[MasterIFSLocationID] [numeric](18, 0) NOT NULL,
	[MasterIFSCondtionID] [numeric](18, 0) NOT NULL,
	[IMEI] [nvarchar](50) NULL,

	[Batch] [nvarchar](25) NULL,
	[isBatchLocked] [Bit] NULL,
	[IFSSiteScan] [nvarchar](5) NULL,
	[IFSProjectScan] [nvarchar](10) NULL,
	[IFSSite] [nvarchar](5) NULL,
	[IFSProject] [nvarchar](10) NULL,
	[POReceiptDate] [nvarchar](10) NULL,

	[SKU] [nvarchar](25) NULL,
	[IFSLocation] [nvarchar](20) NULL,
	[IFSCondition] [nvarchar](50) NULL,
	[IFSConditionCode] [nvarchar](10) NULL,	
	[StatusMessage] [nvarchar](500) NULL,	

    [CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,

 CONSTRAINT [PK_PhysicalInventoryCount] PRIMARY KEY CLUSTERED 
(
	[PhysicalInventoryCountID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

Create Index PHIC_ReceiveDetail on PhysicalInventoryCount(ReceiveDetailID)
Create Index PHIC_MasterIFSLocation on PhysicalInventoryCount(IFSLocation)
Create Index PHIC_MasterIFSCondtion on PhysicalInventoryCount(IFSCondition)
Create Index PHIC_SKU on PhysicalInventoryCount(SKU)
Create Index PHIC_Batch on PhysicalInventoryCount(Batch)




/****** Object:  Table [dbo].[MasterPartsTableIFSLocationLog]    Script Date: 05/07/2015 16:23:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MasterPartsTableIFSLocationStorageChangeLog](
	[MasterPartsTableIFSLocationStorageChangeLogID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[MasterPartsTableIFSLocationStorageID] [numeric](18, 0) NOT NULL,
	[MasterIFSLocationID] [numeric](18, 0) NOT NULL,
	[MasterPartsTechAssignedLogID] [numeric](18, 0) NULL,
	[QTY] [smallint] NULL,
	[QTYChange] [smallint] NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterPartsTableIFSLocationStorageChangeLog] PRIMARY KEY CLUSTERED 
(
	[MasterPartsTableIFSLocationStorageChangeLogID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO




/****** Object:  Table [dbo].[MasterPartsTableIFSLocationStorageMoveLog]    Script Date: 05/07/2015 16:23:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MasterPartsTableIFSLocationStorageMoveLog](
	[MasterPartsTableIFSLocationStorageMoveLogID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[FromMasterPartsTableIFSLocationStorageID] [numeric](18, 0) NULL,
	[ToMasterPartsTableIFSLocationStorageID] [numeric](18, 0) NULL,
    [PartNumberBucketInventorySourceID] [numeric](18, 0) NULL,
    [PartNumberBucketInventoryPlacementID] [numeric](18, 0) NULL,

	[MasterPartsTechAssignedLogID] [numeric](18, 0) NULL,
	[QTY] [smallint] NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterPartsTableIFSLocationStorageMoveLog] PRIMARY KEY CLUSTERED 
(
	[MasterPartsTableIFSLocationStorageMoveLogID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO


















