




















/*

Drop table MasterIFSLocationPurpose
Drop table MasterIFSLocationStatus
Drop table MasterIFSLocation
Drop Table InvtTran_IFS
Drop table MasterIFSLocation


*/

/****** Object:  Table [dbo].MasterIFSLocationPurpose    Script Date: 05/07/2015 16:23:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].MasterIFSLocationPurpose(
	[MasterIFSLocationPurposeID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[Purpose] [varchar](20) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
	[LastUpdateDate] [datetime] NOT NULL,
	[LastUpdateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterIFSLocationPurpose] PRIMARY KEY CLUSTERED 
(
	[MasterIFSLocationPurposeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO



ALTER TABLE [dbo].MasterIFSLocationPurpose ADD  CONSTRAINT [DF_MasterIFSLocationPurpose_CreateDate]  DEFAULT (getdate()) FOR [CreateDate]
GO


Insert MasterIFSLocationPurpose (Purpose, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser) values ('Stock',getdate(), 'jmccomb',getdate(), 'jmccomb')
Insert MasterIFSLocationPurpose (Purpose, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser) values ('Quarantine',getdate(), 'jmccomb',getdate(), 'jmccomb')
Insert MasterIFSLocationPurpose (Purpose, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser) values ('Staging',getdate(), 'jmccomb',getdate(), 'jmccomb')
Insert MasterIFSLocationPurpose (Purpose, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser) values ('Action',getdate(), 'jmccomb',getdate(), 'jmccomb')
Insert MasterIFSLocationPurpose (Purpose, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser) values ('Kan Con',getdate(), 'jmccomb',getdate(), 'jmccomb')


/****** Object:  Table [dbo].MasterIFSLocationStatus    Script Date: 05/07/2015 16:23:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].MasterIFSLocationStatus(
	[MasterIFSLocationStatusID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[Status] [varchar](20) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
	[LastUpdateDate] [datetime] NOT NULL,
	[LastUpdateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterIFSLocationStatus] PRIMARY KEY CLUSTERED 
(
	[MasterIFSLocationStatusID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO



ALTER TABLE [dbo].[MasterIFSLocationStatus] ADD  CONSTRAINT [DF_MasterIFSLocationStatus_CreateDate]  DEFAULT (getdate()) FOR [CreateDate]
GO

Insert MasterIFSLocationStatus (Status, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser)
values ('Active',getdate(), 'jmccomb',getdate(), 'jmccomb')

Insert MasterIFSLocationStatus (Status, CreateDate, CreateUser, LastUpdateDate, LastUpdateUser)
values ('InActive',getdate(), 'jmccomb',getdate(), 'jmccomb')


/*

Drop Table AutoGeneratedPONumbers

*/

/****** Object:  Table [dbo].[AutoGeneratedPONumbers]    Script Date: 05/11/2015 11:59:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AutoGeneratedPONumbers](
	[AutoGeneratedPONumbersID] [numeric](18,0) IDENTITY(1,1) NOT NULL,
	[IFSSite] [nvarchar](5) NULL,
	[IFSProject] [nvarchar](10) NULL,
	[Sku] [nvarchar](25) NULL,
	[IFSCondition] [nvarchar](50) NULL,
	[IFSLocation] [nvarchar](50) NULL,
	[POVendor] [nvarchar](50) NULL,
	[PONumber] [nvarchar](12) NULL,
	[POLine] [nvarchar](5) NULL,
	[StatusID] [numeric](18,0) NULL,         -- 1 = active, 2 = Used
	[CreatedDate] [datetime] NULL,
	[CreateUser] [nvarchar](50) NULL,
	[LastUpdateDate] [datetime] NULL,
	[LastUpdateUser] [nvarchar](50) NULL,

 CONSTRAINT [PK_AutoGeneratedPONumbers] PRIMARY KEY CLUSTERED 
(
	[AutoGeneratedPONumbersID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


Create Index AGPO_PONumber on AutoGeneratedPONumbers(PONumber)
Create Index AGPO_IFSSite on AutoGeneratedPONumbers(IFSSite)
Create Index AGPO_IFSProject on AutoGeneratedPONumbers(IFSProject)
Create Index AGPO_SKU on AutoGeneratedPONumbers(SKU)
Create Index AGPO_IFSCondition on AutoGeneratedPONumbers(IFSCondition)
Create Index AGPO_IFSLocation on AutoGeneratedPONumbers(IFSLocation)
Create Index AGPO_POVendor on AutoGeneratedPONumbers(POVendor)
/*

Drop Table InvtTran_IFS

*/

/****** Object:  Table [dbo].[InvtTran_IFS]    Script Date: 05/11/2015 11:59:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[InvtTran_IFS](
	[InvtTranID] [numeric](18,0) IDENTITY(1,1) NOT NULL,
	[ReceiveDetailID] [numeric](18,0) NULL,
	[ProcessID] [numeric](18, 0) NULL,
	[Quantity] [int] NULL,
	[GMPPartnumber] [nvarchar](30) NULL,	
	[IFSSite] [nvarchar](5) NULL,
	[IFSProject] [nvarchar](10) NULL,
	[POVendor] [nvarchar](50) NULL,
	[PONumber] [nvarchar](12) NULL,
	[POReceiptDate] [nvarchar](10) NULL,
	[POLine] [nvarchar](4) NULL,
	[POCost] [numeric](18, 5) NULL,



	[FromSku] [nvarchar](25) NULL,
	[FromLocation] [nvarchar](50) NULL,
	[FromCondition] [nvarchar](50) NULL,
	[ToSku] [nvarchar](25) NULL,
	[ToLocation] [nvarchar](50) NULL,
	[ToCondition] [nvarchar](50) NULL,
	[ToSKUID] [numeric](18, 0) NULL,
	[ToLocationID] [numeric](18, 0) NULL,
	[ToConditionID] [numeric](18, 0) NULL,
	[Directive] [smallint] NULL,
	[MiscNote] [nvarchar](100) NULL,			
	[StatusID] [numeric](18,0) NULL,
	[CreatedDate] [datetime] NULL,
	[CreateUser] [nvarchar](50) NULL,
	[CreateSource] [nvarchar](25) NULL,
	[RetrievedBatch] [int] NULL,
	[RetrievedDate] [datetime] NULL,
 CONSTRAINT [PK_InvtTran_IFS] PRIMARY KEY CLUSTERED 
(
	[InvtTranID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO




/****** Object:  Table [dbo].MasterIFSLocation    Script Date: 05/07/2015 16:23:38 ******/
SET ANSI_NULLS ON
GO

/*

Drop table MasterIFSLocation
*/

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].MasterIFSLocation(
	[MasterIFSLocationID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[PurposeID] [numeric](18, 0) NOT NULL,
	[StatusID] [numeric](18, 0) NOT NULL,
	[IsWhip] [bit] NOT NULL,
	[IFSLocation] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](100) NULL,
	[DeviceRollup] [nvarchar](50) NULL,
	[PartRollup] [nvarchar](50) NULL,
	[PickLevel] [nvarchar](10) NOT NULL,

	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
	[LastUpdateDate] [datetime] NOT NULL,
	[LastUpdateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterIFSLocation] PRIMARY KEY CLUSTERED 
(
	[MasterIFSLocationID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].MasterIFSLocation ADD  CONSTRAINT [DF_MasterIFSLocation_CreateDate]  DEFAULT (getdate()) FOR [CreateDate]
GO

Create Index MasterIFSLocationPurposeID on MasterIFSLocation([PurposeID])
Go
Create Index MasterIFSLocationStatusID on MasterIFSLocation([StatusID])
Go

/****** Object:  Table [dbo].[MasterPartsTableIFSLocationStorage]    Script Date: 05/07/2015 16:23:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MasterPartsTableIFSLocationStorage](
	[MasterPartsTableIFSLocationStorageID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[MasterPartsTableID] [numeric](18, 0) NOT NULL,
	[MasterIFSLocationID] [numeric](18, 0) NOT NULL,
	[QTY] [smallint] NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
	[LastUpdateDate] [datetime] NOT NULL,
	[LastUpdateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterPartsTableIFSLocationStorage] PRIMARY KEY CLUSTERED 
(
	[MasterPartsTableIFSLocationStorageID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO


/****** Object:  Table [dbo].[PhysicalInventoryCount]    Script Date: 05/07/2015 16:23:38 ******/
SET ANSI_NULLS ON
GO

/*

Drop Table PhysicalInventoryCount

*/

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PhysicalInventoryCount](
	[PhysicalInventoryCountID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ReceiveDetailID] [numeric](18, 0) NOT NULL,
	[MasterIFSLocationID] [numeric](18, 0) NOT NULL,
	[MasterIFSCondtionID] [numeric](18, 0) NOT NULL,
	[IMEI] [nvarchar](50) NULL,

	[Batch] [nvarchar](25) NULL,
	[isBatchLocked] [Bit] NULL,
	[IFSSiteScan] [nvarchar](5) NULL,
	[IFSProjectScan] [nvarchar](10) NULL,
	[IFSSite] [nvarchar](5) NULL,
	[IFSProject] [nvarchar](10) NULL,
	[POReceiptDate] [nvarchar](10) NULL,

	[SKU] [nvarchar](25) NULL,
	[IFSLocation] [nvarchar](20) NULL,
	[IFSCondition] [nvarchar](50) NULL,
	[IFSConditionCode] [nvarchar](10) NULL,	
	[StatusMessage] [nvarchar](500) NULL,	

    [CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,

 CONSTRAINT [PK_PhysicalInventoryCount] PRIMARY KEY CLUSTERED 
(
	[PhysicalInventoryCountID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

Create Index PHIC_ReceiveDetail on PhysicalInventoryCount(ReceiveDetailID)
Create Index PHIC_MasterIFSLocation on PhysicalInventoryCount(IFSLocation)
Create Index PHIC_MasterIFSCondtion on PhysicalInventoryCount(IFSCondition)
Create Index PHIC_SKU on PhysicalInventoryCount(SKU)
Create Index PHIC_Batch on PhysicalInventoryCount(Batch)




/****** Object:  Table [dbo].[MasterPartsTableIFSLocationLog]    Script Date: 05/07/2015 16:23:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MasterPartsTableIFSLocationStorageChangeLog](
	[MasterPartsTableIFSLocationStorageChangeLogID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[MasterPartsTableIFSLocationStorageID] [numeric](18, 0) NOT NULL,
	[MasterIFSLocationID] [numeric](18, 0) NOT NULL,
	[MasterPartsTechAssignedLogID] [numeric](18, 0) NULL,
	[QTY] [smallint] NULL,
	[QTYChange] [smallint] NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterPartsTableIFSLocationStorageChangeLog] PRIMARY KEY CLUSTERED 
(
	[MasterPartsTableIFSLocationStorageChangeLogID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO




/****** Object:  Table [dbo].[MasterPartsTableIFSLocationStorageMoveLog]    Script Date: 05/07/2015 16:23:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MasterPartsTableIFSLocationStorageMoveLog](
	[MasterPartsTableIFSLocationStorageMoveLogID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[FromMasterPartsTableIFSLocationStorageID] [numeric](18, 0) NULL,
	[ToMasterPartsTableIFSLocationStorageID] [numeric](18, 0) NULL,
    [PartNumberBucketInventorySourceID] [numeric](18, 0) NULL,
    [PartNumberBucketInventoryPlacementID] [numeric](18, 0) NULL,

	[MasterPartsTechAssignedLogID] [numeric](18, 0) NULL,
	[QTY] [smallint] NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MasterPartsTableIFSLocationStorageMoveLog] PRIMARY KEY CLUSTERED 
(
	[MasterPartsTableIFSLocationStorageMoveLogID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

















































































/****** Object:  View [dbo].[vwIFS_InvtTran]    Script Date: 05/11/2015 12:11:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




/*

Select * from vwIFS_InvtTran_B
Select * from InvtTran_IFS

ALTER TABLE InvtTran_IFS drop COLUMN FromValuePct
go
ALTER TABLE InvtTran_IFS drop COLUMN ToValuePct
go

*/




ALTER VIEW [dbo].[vwIFS_InvtTran]
AS
SELECT     ReceiveDetail.ReceiveDetailID, ReceiveDetail.ESN, ReceiveDetail.Version, InvtTran_IFS.InvtTranID
                    , InvtTran_IFS.IFSSite
					, InvtTran_IFS.IFSProject
					, InvtTran_IFS.POVendor
					, InvtTran_IFS.PONumber
					, InvtTran_IFS.POReceiptDate

					, InvtTran_IFS.POLine
					, InvtTran_IFS.POCost
                    , InvtTran_IFS.Quantity
                    , InvtTran_IFS.GMPPartNumber

                    , InvtTran_IFS.FromSku
					, InvtTran_IFS.FromLocation
					, InvtTran_IFS.FromCondition
					, InvtTran_IFS.ToSku
					, InvtTran_IFS.ToLocation
					, InvtTran_IFS.ToCondition, InvtTran_IFS.CreatedDate, InvtTran_IFS.CreateUser, 
                      InvtTran_IFS.Directive, InvtTran_IFS.CreateSource, InvtTran_IFS.RetrievedBatch, InvtTran_IFS.RetrievedDate, InvtTran_IFS.ProcessID, Process.Name AS Process, 
                      InvtTran_IFS.ToSKUID, InvtTran_IFS.ToLocationID, InvtTran_IFS.ToConditionID
                    , InvtTran_IFS.MiscNote, InvtTran_IFS.StatusID
FROM         InvtTran_IFS INNER JOIN
                      ReceiveDetail ON ReceiveDetail.ReceiveDetailID = InvtTran_IFS.ReceiveDetailID INNER JOIN
                      Process ON InvtTran_IFS.ProcessID = Process.ProcessID







GO




















/****** Object:  StoredProcedure [dbo].[Update_ReceiveDetailPhysicalScan]    Script Date: 05/19/2015 23:20:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
/*

Declare	@PONumber nvarchar(50)
Declare @POLine nvarchar(5)
    
Exec GetNextPONumberAndLine
	'Site',
	'IFSProject',
	'POVendor1',
	'jmccomb',
	@PONumber output,
    @POLine Output
    
Print  	@PONumber
Print   @POLine   


Select * from AutoGeneratedPONumbers

*/



Alter PROCEDURE [dbo].[GetNextPONumberAndLine]
	@IFSSite nvarchar(5),
	@IFSProject nvarchar(10),
	--@SKU nvarchar(25),
	--@IFSLocation nvarchar(20),
	--@IFSCondition nvarchar(50),
	@POVendor nvarchar(50),
	@UserName nvarchar(50),
	@PONumber nvarchar(50) output,
    @POLine [nvarchar](5) Output
AS
BEGIN
set nocount on
Declare @_POLine [nvarchar](5) 
Declare @AutoGeneratedPONumbersID [numeric](18,0)

Select @AutoGeneratedPONumbersID = AutoGeneratedPONumbersID,
       @_POLine = POLine, 
       @PONumber = PONumber from AutoGeneratedPONumbers where IFSSite = @IFSSite
                                                 and IFSProject = @IFSProject
                                                 and POVendor = @POVendor
												 and StatusID = 1

if isnull(@AutoGeneratedPONumbersID,-1) > 0
   begin
   Select @_POLine = POLine, 
          @PONumber = PONumber from AutoGeneratedPONumbers where IFSSite = @IFSSite
                                                 and IFSProject = @IFSProject
                                                 and POVendor = @POVendor
												 and StatusID = 1
   Select @_POLine = @_POLine + 1
   Update AutoGeneratedPONumbers set POLine = @_POLine, LastUpdateDate = getdate(), LastUpdateUser =  @UserName
    where AutoGeneratedPONumbersID = @AutoGeneratedPONumbersID
   Select @POLine = @_POLine
   return
   end


Select Top 1 @PONumber = PONumber from AutoGeneratedPONumbers order by PONumber Desc
if (len(isnull(@PONumber,'')) < 12)
   Select @PONumber = 'BRC000000000'
Declare @Counter numeric(9)
Select @Counter = convert(Numeric(9),Substring(@PONumber,4,9))
Select @Counter = @Counter + 1
Select @POLine = 1
Select @PONumber = 'BRC' + Right('000000000' + convert(nvarchar(9),@Counter),9)

Insert AutoGeneratedPONumbers (
      [IFSSite],
	  [IFSProject],
	  [Sku],
	  [IFSCondition],
	  [IFSLocation],
	  [POVendor],
	  [PONumber],
	  [POLine],
	  [StatusID],
	  [CreatedDate],
	  [CreateUser],
	  [LastUpdateDate],
	  [LastUpdateUser])
Values(@IFSSite,
       @IFSProject,
	   '',
	   '',
	   '',
	   @POVendor,
	   @PONumber,
	   @POLine,
	   1,
	   getdate(),
	   @UserName,
	   getdate(),
	   @UserName
     )

       
Return 0

END





/****** Object:  StoredProcedure [dbo].[GetMasterProjectList]    Script Date: 05/15/2015 09:57:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================

/*

exec GetPhysicalInventoryCountList 'batch'


*/

Create PROCEDURE [dbo].[GetPhysicalInventoryCountList]
      @Batch nvarchar(50)

AS
BEGIN
	SET NOCOUNT ON;


SELECT     PhysicalInventoryCount.*
FROM         PhysicalInventoryCount where Batch = @Batch

END






/****** Object:  StoredProcedure [dbo].[IFS_GenerateInvtTran]    Script Date: 05/11/2015 12:41:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================

/*

exec IFS_GenerateInvtTran 1118447,  'LOC', 'jmccomb'

*/



ALTER PROCEDURE [dbo].[IFS_GenerateInvtTran]
      @mReceiveDetailID numeric(18),
      @mS nvarchar(1),
      @mL nvarchar(1),
      @mC nvarchar(1),            
      @mUserName nvarchar(50)

AS
BEGIN
	SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED	

Declare @IsFirst smallint

Declare @LastFromSku nvarchar(25)
Declare @LastFromLocation [nvarchar](50)
Declare @LastFromCondition [nvarchar](50)
Declare @LastToSku nvarchar(25)
Declare @LastToLocation [nvarchar](50)
Declare @LastToCondition [nvarchar](50)

Declare @FromSku nvarchar(25)
Declare @FromLocation [nvarchar](50)
Declare @FromCondition [nvarchar](50)
Declare @ToSku nvarchar(25)
Declare @ToLocation [nvarchar](50)
Declare @ToCondition [nvarchar](50)

Declare @ToSKUID numeric(18)
Declare @ToLocationID numeric(18)
Declare @ToConditionID numeric(18)

Declare @IFSSite [nvarchar](5)
Declare @IFSProject [nvarchar](10)
Declare @POVendor [nvarchar](50)
Declare @PONumber [nvarchar](12)
Declare @POReceiptDate [nvarchar](10)
Declare @POLine [nvarchar](4)	
Declare @POCostString [nvarchar](20)	
Declare @POCost [numeric](18, 5)
Declare @ProcessID numeric(18)


Select @IFSProject = IFSProject, @IFSSite = IFSSite from ReceiveDetail Inner join ClientLocation on ClientLocation.ClientLocationID = ReceiveDetail.ClientLocationID Where ReceiveDetail.ReceiveDetailID = @mReceiveDetailID
Select @ProcessID = dbo.GetReceivedDetailCurrentProcessID(ReceiveDetail.ReceiveDetailID) from ReceiveDetail where ReceiveDetailID = @mReceiveDetailID
Select @PONumber = ''
Select @POLine = ''
Select @POCostString = ''
Select @POCost = 0

-- Get the From and To SKU -----------------------------------------------------------------
Select Top 1 @ToSKU = SKU, @ToSKUID = ReceiveDetailSKUChangeLogID From ReceiveDetailSKUChangeLog where ReceiveDetailID = @mReceiveDetailID Order by CreateDate Desc
Select @FromSku = @ToSKU
-- Get the From and To Locations -----------------------------------------------------------------
Select Top 1 @ToLocation = IFSLocation, @ToLocationID = ReceiveDetailIFSLocationLogID  From ReceiveDetailIFSLocationLog where ReceiveDetailID = @mReceiveDetailID Order by CreateDate Desc
Select @FromLocation = @ToLocation 
-- Get the From and To Condition -----------------------------------------------------------------
Select Top 1 @ToCondition = IFS_Condition, @ToConditionID = ReceiveDetailConditionChangeLogID  From ReceiveDetailConditionChangeLog where ReceiveDetailID = @mReceiveDetailID Order by CreateDate Desc
Select @FromCondition = @ToCondition 


-- If the Source is "LOC" then we need a from location, otherwise stays is equal to the "TO" location 
if (@mL = 'L')
    begin
    Select @FromLocation = ''
    Select Top 1 @FromLocation = IFSLocation From ReceiveDetailIFSLocationLog where ReceiveDetailID = @mReceiveDetailID and ReceiveDetailIFSLocationLogID != @ToLocationID Order by CreateDate Desc
    end

-- If the Source is "COND" then we need a from Condition, otherwise it stays equal to the "TO" Condition 
if (@mC = 'C')
    begin
    Select @FromCondition = ''
    Select Top 1 @FromCondition = IFS_Condition From ReceiveDetailConditionChangeLog where ReceiveDetailID = @mReceiveDetailID and ReceiveDetailConditionChangeLogID != @ToConditionID Order by CreateDate Desc
    end
-- Get the Value Percentage

-- If the Source is "SKU" then we need a from SKU, otherwise it is equal stays the "TO" SKU
if (@mS = 'S')
    begin
    select @FromSKU = ''
    Select Top 1 @FromSKU = SKU From ReceiveDetailSKUChangeLog where ReceiveDetailID = @mReceiveDetailID and ReceiveDetailSKUChangeLogID != @ToSKUID Order by CreateDate Desc
    end


------------------------------------------------------------------------------------------------------
-- Now we need to add the new transaction.
Select @IsFirst = 1       -- Assume all transactions are the first
-- IF we have an earlier transaction for thie Device, then it is not the first one
if exists(Select * From InvtTran_IFS where ReceiveDetailID = @mReceiveDetailID)
   Select @IsFirst = 0

if LEN(@ToLocation) = 0 
   Select @IsFirst = 2            -- SOLD, Left the building
   
   
if @IsFirst = 1
   begin
   Select @PONumber = [dbo].[GetReceivedQuestionAnswerString](@mReceiveDetailID,'IFS PO Number')
   Select @POLine = [dbo].[GetReceivedQuestionAnswerString](@mReceiveDetailID,'IFS PO Line Number')
   Select @POCostString = [dbo].[GetReceivedQuestionAnswerString](@mReceiveDetailID,'IFS PO Unit Cost')
   Select @POVendor =  [dbo].[GetReceivedQuestionAnswerString](@mReceiveDetailID,'IFS PO Vendor')
   Select @POReceiptDate = [dbo].[GetReceivedQuestionAnswerString](@mReceiveDetailID,'IFS PO Receipt Date')
   Select @POCost = 0
   if ISNUMERIC(@POCostString) = 1
      Select @POCost = CONVERT(numeric(18,5),@POCostString)   

   if len(@PONumber) = 0
      begin
      Declare @PONumberx nvarchar(50)
      Declare @POLinex nvarchar(5)
    
      Exec GetNextPONumberAndLine
           @IFSSite,
           @IFSProject,
           @POVendor,
           @mUserName,
           @PONumberx output,
           @POLinex Output
      Select @PONumber = @PONumberx
      Select @POLine = @POLinex
      exec [dbo].[UpdateESNAttribute_BYID] @mReceiveDetailID, 'IFS PO Number', @PONumber, @mUserName
      exec [dbo].[UpdateESNAttribute_BYID] @mReceiveDetailID, 'IFS PO Line Number', @POLine, @mUserName
	  end
   end   

-- Get the data from the last one.   
Select Top 1 @LastFromLocation = FromLocation, @LastToLocation = ToLocation,  
             @LastFromCondition = FromCondition, @LastToCondition = ToCondition, 
             @LastFromSku = FromSku, @LastToSku = ToSku
 From InvtTran_IFS where ReceiveDetailID = @mReceiveDetailID Order by CreatedDate Desc

if isnull(@LastFromLocation,'') != isnull(@FromLocation,'') or isnull(@LastToLocation,'') != isnull(@ToLocation,'')
or isnull(@LastFromCondition,'') != isnull(@FromCondition,'') or isnull(@LastToCondition,'') != isnull(@ToCondition,'')
or isnull(@LastFromSKU,'') != isnull(@FromSKU,'') or isnull(@LastToSKU,'') != isnull(@ToSKU,'')
   begin
   if isnull(@FromLocation,'') != isnull(@ToLocation,'')
   or isnull(@FromCondition,'') != isnull(@ToCondition,'')
   or isnull(@FromSKU,'') != isnull(@ToSKU,'')
   Insert InvtTran_IFS (ReceiveDetailID, FromSKU
                      , IFSSite, IFSProject, POVendor, PONumber,POReceiptDate, POLine, POCost
                      , FromLocation, FromCondition, ToSku, ToLocation, ToCondition, CreatedDate, CreateUser, CreateSource, ProcessID, ToSkuID, ToLocationID, ToConditionID, Directive )
   Values (@mReceiveDetailID, @FromSku
          ,@IFSSite
          ,@IFSProject
		  ,@POVendor
          ,@PONumber
		  ,@POReceiptDate
          ,@POLine
          ,@POCost
          ,@FromLocation,@FromCondition, @ToSku, @ToLocation, @ToCondition, getdate(), @mUserName, ltrim(rtrim(@mS)) + ltrim(rtrim(@mL)) + ltrim(rtrim(@mC)), @ProcessID, @ToSKUID,@ToLocationID ,@ToConditionID, @IsFirst ) 
   end
END




GO


/****** Object:  StoredProcedure [dbo].[Update_ReceiveDetailPhysicalScan]    Script Date: 05/19/2015 23:20:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[ResetNextPONumberAndLine]
	@UserName nvarchar(50)
AS
BEGIN
       
Update AutoGeneratedPONumbers set StatusID = 2, LastUpdateDate = getdate(), LastUpdateUser = @UserName where StatusID = 1
       
Return 0

END





/****** Object:  StoredProcedure [dbo].[Update_ReceiveDetailPhysicalScan]    Script Date: 05/19/2015 23:20:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[Update_ReceiveDetailPhysicalScan]
	@MasterIFSLocationID numeric(18, 0),
	@MasterIFSCondtionID numeric(18, 0), 
	@ESN nvarchar(50),
	@Batch nvarchar(25),	
	@IFSSiteScan nvarchar(5),
	@IFSProjectScan nvarchar(10),
	@IFSPOReceiptDate nvarchar(10),
	@SKU nvarchar(25),
	@IFSLocation nvarchar(20),
	@IFSCondition nvarchar(50),
	@UpdateIMEI bit,
	@UserName nvarchar(50)
AS
BEGIN
Declare @IFSSite nvarchar(5)
Declare	@IFSProject nvarchar(10)

Declare @ReceiveDetailID numeric(18,0)
Declare @ClientLocationID numeric(18,0)
Declare @Message nvarchar(100)
Declare @IFSConditionCode nvarchar(10)
Select @Message = 'Scanned'
Select @IFSConditionCode = ''

Select @ReceiveDetailID = ReceiveDetailID, @ClientLocationID = ClientLocationID from ReceiveDetail where ESN = @ESN and Version = '000'
Select @ReceiveDetailID = ISNULL(@ReceiveDetailID,-1)
if (@ReceiveDetailID < 1)
    select @Message = 'IMEI, version 000 not found!'



Select @IFSConditionCode = Name from [Option] where OptionID = @MasterIFSCondtionID
if (@ReceiveDetailID > 1)
    begin
    Select @SKU = dbo.GetIFSSKU(@ReceiveDetailID)
    if @UpdateIMEI = 1         -- true
       begin
       Select @IFSSite = isnull(IFSSite, ''),  @IFSProject = isnull(IFSProject,'') from ClientLocation where ClientLocationID = @ClientLocationID
	   --if (len(@IFSSite) > 0 or len(@IFSProject) > 0)
	      --begin
          --Update ClientLocation set IFSSite = case when len(@IFSSite) = 0 then IFSSite else @IFSSite end
	         --                      ,IFSProject = case when len(@IFSProject) = 0 then IFSProject else @IFSProject end
          --where ClientLocationID = @ClientLocationID
		  --end
       Update ReceiveDetail set IFSLocation = @IFSLocation, SKU = @SKU, IFSCondition = @IFSConditionCode where ReceiveDetailID = @ReceiveDetailID
       exec [dbo].[UpdateESNAttribute_BYID] @ReceiveDetailID, 'IFS Conditions', @IFSCondition, @UserName
       Select @Message = 'Updated'
	   if @IFSSite != @IFSSiteScan
	      begin
          Select @Message = @Message + '/Scanned Site(' + @IFSSiteScan + ') != Actual Site:' + @IFSSite
		  end
	   if @IFSProject != @IFSProjectScan
	      begin
          Select @Message = @Message + '/Scanned Project(' + @IFSProjectScan + ') != Actual Project:' + @IFSProject
		  end


       end
    end
    

--Select * from [PhysicalInventoryCount]

Insert [PhysicalInventoryCount](
       [ReceiveDetailID]
      ,[MasterIFSLocationID]
      ,[MasterIFSCondtionID]
      ,[IMEI]
      ,[Batch]
      ,[IFSSiteScan]
      ,[IFSProjectScan]
      ,[IFSSite]
      ,[IFSProject]
      ,[SKU]
      ,[IFSLocation]
      ,[IFSCondition]
      ,[IFSConditionCode]
	  ,[POReceiptDate]
      ,[StatusMessage]
      ,[CreateDate]
      ,[CreateUser])
values (@ReceiveDetailID
       ,@MasterIFSLocationID
       ,@MasterIFSCondtionID
       ,@ESN
       ,@Batch
       ,@IFSSiteScan
       ,@IFSProjectScan
	   ,@IFSSite
	   ,@IFSProject
       ,@SKU
       ,@IFSLocation
       ,@IFSCondition
       ,@IFSConditionCode
       ,@IFSPOReceiptDate
       ,@Message
       ,getdate()
       ,@UserName)
       
       
Return 0

END









--/****** Object:  Table [dbo].MasterIFSLocation    Script Date: 05/07/2015 16:23:38 ******/
--SET ANSI_NULLS ON
--GO

--/*

--Drop table MasterIFSLocation
--*/

--SET QUOTED_IDENTIFIER ON
--GO

--CREATE TABLE [dbo].MasterIFSLocation(
--	[MasterIFSLocationID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
--	[PurposeID] [numeric](18, 0) NOT NULL,
--	[StatusID] [numeric](18, 0) NOT NULL,
--	[IsWhip] [bit] NOT NULL,
--	[IFSLocation] [nvarchar](50) NOT NULL,
--	[Description] [nvarchar](100) NULL,
--	[DeviceRollup] [nvarchar](50) NULL,
--	[PartRollup] [nvarchar](50) NULL,
--	[PickLevel] [nvarchar](10) NOT NULL,

--	[CreateDate] [datetime] NOT NULL,
--	[CreateUser] [nvarchar](50) NOT NULL,
--	[LastUpdateDate] [datetime] NOT NULL,
--	[LastUpdateUser] [nvarchar](50) NOT NULL,
-- CONSTRAINT [PK_MasterIFSLocation] PRIMARY KEY CLUSTERED 
--(
--	[MasterIFSLocationID] ASC
--)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 75) ON [PRIMARY]
--) ON [PRIMARY]

--GO

--ALTER TABLE [dbo].MasterIFSLocation ADD  CONSTRAINT [DF_MasterIFSLocation_CreateDate]  DEFAULT (getdate()) FOR [CreateDate]
--GO

--Create Index MasterIFSLocationPurposeID on MasterIFSLocation([PurposeID])
--Go
--Create Index MasterIFSLocationStatusID on MasterIFSLocation([StatusID])
--Go



















/****** Object:  Trigger [dbo].[ProcessStepChange]    Script Date: 05/12/2015 18:55:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================

CREATE TRIGGER [dbo].[RecordStorageChangePlacement]
   ON  [dbo].[PartNumberBucketInventoryPlacement]
  AFTER UPDATE, INSERT
AS 
BEGIN

	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON;
    
IF (SELECT COUNT(*) FROM inserted) > 0 and (SELECT COUNT(*) FROM Deleted) < 1
 BEGIN

       INSERT INTO [GMP_Data].[dbo].[MasterPartsTableIFSLocationStorage]
           ([MasterPartsTableID]
           ,[MasterIFSLocationID]
           ,[QTY]
           ,[CreateDate]
           ,[CreateUser]
           ,[LastUpdateDate]
           ,[LastUpdateUser])
       Select MasterPartsLinkTableID
             ,MasterIFSLocationID
             ,0
             , LastUpdateDate
             , LastUpdateUser
             , LastUpdateDate
             , LastUpdateUser
      from inserted where MasterIFSLocationID not in (select MasterIFSLocationID from [MasterPartsTableIFSLocationStorage])
      
      Insert into [MasterPartsTableIFSLocationStorageMoveLog]  (FromMasterPartsTableIFSLocationStorageID
                                                             ,ToMasterPartsTableIFSLocationStorageID
                                                             ,PartNumberBucketInventorySourceID
                                                             ,PartNumberBucketInventoryPlacementID
                                                             ,MasterPartsTechAssignedLogID
                                                             ,QTY
                                                             ,CreateDate
                                                             ,CreateUser)
    Select MasterPartsTableIFSLocationStorageID
          ,MasterPartsTableIFSLocationStorageID
          ,null
          ,PartNumberBucketInventoryPlacementID
          ,null
          ,inserted.Quantity
          ,GETDATE()
          ,inserted.LastUpdateUser
          
     from inserted   
     inner join MasterPartsTableIFSLocationStorage on MasterPartsTableIFSLocationStorage.MasterIFSLocationID = inserted.MasterIFSLocationID
     
     
     Update MasterPartsTableIFSLocationStorage set QTY = QTY + inserted.quantity
     from inserted   
     inner join MasterPartsTableIFSLocationStorage on MasterPartsTableIFSLocationStorage.MasterIFSLocationID = inserted.MasterIFSLocationID
  
   RETURN
 END

    -- Insert statements for trigger here

END



GO




/****** Object:  Trigger [dbo].[ProcessStepChange]    Script Date: 05/12/2015 18:55:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================

CREATE TRIGGER [dbo].[RecordStorageChange]
   ON  [dbo].[PartNumberBucketInventorySource]
  AFTER UPDATE, INSERT
AS 
BEGIN

	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON;
    
IF (SELECT COUNT(*) FROM inserted) > 0 and (SELECT COUNT(*) FROM Deleted) < 1
 BEGIN

       INSERT INTO [GMP_Data].[dbo].[MasterPartsTableIFSLocationStorage]
           ([MasterPartsTableID]
           ,[MasterIFSLocationID]
           ,[QTY]
           ,[CreateDate]
           ,[CreateUser]
           ,[LastUpdateDate]
           ,[LastUpdateUser])
       Select MasterPartsLinkTableID
             ,MasterIFSLocationID
             ,0
             , LastUpdateDate
             , LastUpdateUser
             , LastUpdateDate
             , LastUpdateUser
      from inserted where MasterIFSLocationID not in (select MasterIFSLocationID from [MasterPartsTableIFSLocationStorage])
      
      Insert into [MasterPartsTableIFSLocationStorageMoveLog]  (FromMasterPartsTableIFSLocationStorageID
                                                             ,ToMasterPartsTableIFSLocationStorageID
                                                             ,PartNumberBucketInventorySourceID
                                                             ,PartNumberBucketInventoryPlacementID
                                                             ,MasterPartsTechAssignedLogID
                                                             ,QTY
                                                             ,CreateDate
                                                             ,CreateUser)
    Select MasterPartsTableIFSLocationStorageID
          ,MasterPartsTableIFSLocationStorageID
          ,PartNumberBucketInventorySourceID
          ,null
          ,null
          ,inserted.Quantity
          ,GETDATE()
          ,inserted.LastUpdateUser
          
     from inserted   
     inner join MasterPartsTableIFSLocationStorage on MasterPartsTableIFSLocationStorage.MasterIFSLocationID = inserted.MasterIFSLocationID
     
     
     Update MasterPartsTableIFSLocationStorage set QTY = QTY + inserted.quantity
     from inserted   
     inner join MasterPartsTableIFSLocationStorage on MasterPartsTableIFSLocationStorage.MasterIFSLocationID = inserted.MasterIFSLocationID
  
   RETURN
 END

    -- Insert statements for trigger here

END



GO



/****** Object:  Trigger [dbo].[ProcessStepChange]    Script Date: 05/11/2015 12:38:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================

ALTER TRIGGER [dbo].[ProcessStepChange]
   ON  [dbo].[ReceiveDetail]
  AFTER UPDATE, INSERT
AS 
BEGIN


	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON;
	
	
Declare @mReceiveDetailID numeric(18)
Declare @mUserName nvarchar(50)
Declare @List Table (ReceiveDetailID numeric(18))
Declare @mS nvarchar(1)
Declare @mL nvarchar(1)
Declare @mC nvarchar(1)
Select @mS = ' '
Select @mL = ' '
Select @mC = ' '



    
IF (SELECT COUNT(*) FROM inserted) > 0 and (SELECT COUNT(*) FROM Deleted) < 1
 BEGIN
    Insert into ReceiveDetailVersionChangeLog  (ReceiveDetailID,Version,CreateDate,CreateUser)
    Select ReceiveDetailID,Version,LastUpdateDate,LastUpdateUser from inserted 
    
    Insert into ReceiveDetailSKUChangeLog (ReceiveDetailID, SKU, CreateDate,CreateUser)
    Select ReceiveDetailID, SKU, getdate(),LastUpdateUser from inserted 
    where not inserted.SKU is null  
    
     Insert into ReceiveDetailIFSLocationLog (ReceiveDetailID, IFSLocation, MiscText, CreateDate,CreateUser)
    Select ReceiveDetailID, IFSLocation, '', getdate(),LastUpdateUser from inserted 
    where not inserted.IFSLocation is null   
    
    Insert into ReceiveDetailConditionChangeLog (ReceiveDetailID, IFS_Condition, CreateDate,CreateUser)
    Select ReceiveDetailID, IFSCondition, getdate(),LastUpdateUser from inserted 
    where not inserted.IFSCondition is null    
    Select @mS = 'S'
    Select @mL = 'L'
    Select @mC = 'C'
    
    While exists (Select ReceiveDetailID from inserted where not ReceiveDetailID in (Select ReceiveDetailID from @List))
    begin
          Select Top 1 @mReceiveDetailID = ReceiveDetailID, @mUserName = CreateUser from inserted where not ReceiveDetailID in (Select ReceiveDetailID from @List)
          insert @List (ReceiveDetailID) values (@mReceiveDetailID)
          exec IFS_GenerateInvtTran @mReceiveDetailID, @mS, @mL, @mC, @mUserName
    end 
  
   RETURN
 END

IF UPDATE(Version)
   BEGIN
   Insert into ReceiveDetailVersionChangeLog  (ReceiveDetailID,Version,CreateDate,CreateUser)
   Select ReceiveDetailID,Version,LastUpdateDate,LastUpdateUser from inserted 
   --RETURN
   END

IF UPDATE(SKU)
   BEGIN
    Select @mS = 'S'
   Insert into ReceiveDetailSKUChangeLog (ReceiveDetailID, SKU, CreateDate,CreateUser)
   Select ReceiveDetailID, SKU, getdate(),LastUpdateUser from inserted 
   where not inserted.SKU is null   
   --RETURN
   END
   
IF UPDATE(IFSLocation)
   BEGIN
    Select @mL = 'L'
    Insert into ReceiveDetailIFSLocationLog (ReceiveDetailID, IFSLocation, MiscText, CreateDate,CreateUser)
    Select ReceiveDetailID, IFSLocation, '', GETDATE(),LastUpdateUser from inserted 
    where not inserted.IFSLocation is null    
   --RETURN
   END

IF UPDATE(IFSCondition)
   BEGIN
    Select @mC = 'C'
    Insert into ReceiveDetailConditionChangeLog (ReceiveDetailID, IFS_Condition, CreateDate,CreateUser)
    Select inserted.ReceiveDetailID, inserted.IFSCondition, getdate(),inserted.LastUpdateUser from inserted 
    where not inserted.IFSCondition is null 
   END
   
if UPDATE(ProcessID)
   BEGIN
   Declare @mProcessID numeric(18)
   Select @mProcessID = ProcessID from inserted
   Declare @mProcessName nvarchar(20)
   Select @mProcessName = Name from Process where ProcessID = @mProcessID

   Insert into ReceiveDetailProcessLog (ReceiveDetailID,ProcessID,ProcessText,MiscText,CreateDate,CreateUser)
   Select ReceiveDetailID,ProcessID,@mProcessName,'',LastUpdateDate,LastUpdateUser
   from inserted
   END
   
   
   
 IF UPDATE(SKU)or UPDATE(IFSLocation) or UPDATE(IFSCondition)
 BEGIN
    
    While exists (Select ReceiveDetailID from inserted where not ReceiveDetailID in (Select ReceiveDetailID from @List))
    begin
    Select Top 1 @mReceiveDetailID = ReceiveDetailID, @mUserName = CreateUser from inserted where not ReceiveDetailID in (Select ReceiveDetailID from @List)
    insert @List (ReceiveDetailID) values (@mReceiveDetailID)
    exec IFS_GenerateInvtTran @mReceiveDetailID, @mS, @mL, @mC, @mUserName
    end
END
    -- Insert statements for trigger here

END



GO


























































