/*

Drop Table AutoGeneratedPONumbers_B

*/

/****** Object:  Table [dbo].[AutoGeneratedPONumbers]    Script Date: 05/11/2015 11:59:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AutoGeneratedPONumbers_B](
	[AutoGeneratedPONumbersID] [numeric](18,0) IDENTITY(1,1) NOT NULL,
	[IFSSite] [nvarchar](5) NULL,
	[IFSProject] [nvarchar](10) NULL,
	[Sku] [nvarchar](25) NULL,
	[IFSCondition] [nvarchar](50) NULL,
	[IFSLocation] [nvarchar](50) NULL,
	[POVendor] [nvarchar](50) NULL,
	[PONumber] [nvarchar](12) NULL,
	[POLine] [smallint] NULL,
	[StatusID] [numeric](18,0) NULL,         -- 1 = active, 2 = Used
	[CreatedDate] [datetime] NULL,
	[CreateUser] [nvarchar](50) NULL,
	[LastUpdateDate] [datetime] NULL,
	[LastUpdateUser] [nvarchar](50) NULL,

 CONSTRAINT [PK_AutoGeneratedPONumbers_B] PRIMARY KEY CLUSTERED 
(
	[AutoGeneratedPONumbersID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


Create Index AGPO_PONumber_B on AutoGeneratedPONumbers_B(PONumber)
Create Index AGPO_IFSSite_B on AutoGeneratedPONumbers_B(IFSSite)
Create Index AGPO_IFSProject_B on AutoGeneratedPONumbers_B(IFSProject)
Create Index AGPO_SKU_B on AutoGeneratedPONumbers_B(SKU)
Create Index AGPO_Line_B on AutoGeneratedPONumbers_B(POLine)
-- Create Index AGPO_IFSCondition on AutoGeneratedPONumbers(IFSCondition)
-- Create Index AGPO_IFSLocation on AutoGeneratedPONumbers(IFSLocation)
Create Index AGPO_StatusID_B on AutoGeneratedPONumbers_B(StatusID)
Create Index AGPO_POVendor_B on AutoGeneratedPONumbers_B(POVendor)
